apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/standard-install.yaml
  - ./gatewayclass.yaml
  - ./gateway.yaml
  - ./lb-ip-pool.yaml
  - ./l2announcement-policy.yaml
  - helm/cilium/templates/cilium-agent/clusterrolebinding.yaml
  - helm/cilium/templates/cilium-agent/clusterrole.yaml
  - helm/cilium/templates/cilium-agent/daemonset.yaml
  - helm/cilium/templates/cilium-agent/rolebinding.yaml
  - helm/cilium/templates/cilium-agent/role.yaml
  - helm/cilium/templates/cilium-agent/serviceaccount.yaml
  - helm/cilium/templates/cilium-configmap.yaml
  - helm/cilium/templates/cilium-envoy/configmap.yaml
  - helm/cilium/templates/cilium-envoy/daemonset.yaml
  - helm/cilium/templates/cilium-envoy/serviceaccount.yaml
  - helm/cilium/templates/cilium-envoy/service.yaml
  - helm/cilium/templates/cilium-operator/clusterrolebinding.yaml
  - helm/cilium/templates/cilium-operator/clusterrole.yaml
  - helm/cilium/templates/cilium-operator/deployment.yaml
  - helm/cilium/templates/cilium-operator/rolebinding.yaml
  - helm/cilium/templates/cilium-operator/role.yaml
  - helm/cilium/templates/cilium-operator/serviceaccount.yaml
  - helm/cilium/templates/cilium-secrets-namespace.yaml
  - helm/cilium/templates/hubble/peer-service.yaml
  - helm/cilium/templates/hubble/tls-cronjob/cronjob.yaml
  - helm/cilium/templates/hubble/tls-cronjob/job.yaml
  - helm/cilium/templates/hubble/tls-cronjob/rolebinding.yaml
  - helm/cilium/templates/hubble/tls-cronjob/role.yaml
  - helm/cilium/templates/hubble/tls-cronjob/serviceaccount.yaml
