apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-policy
spec:
  serviceSelector:
    matchLabels: {}
  nodeSelector:
    matchLabels: {}
  interfaces:
    - "^eth[0-9]+"
  externalIPs: true
  loadBalancerIPs: true
