---
# Source: argo-cd/templates/argocd-configs/argocd-rbac-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: kube-system
  labels:
    helm.sh/chart: argo-cd-8.3.0
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: "v3.1.0"
data:
  policy.csv: ""
  policy.default: ""
  policy.matchMode: glob
  scopes: "[groups]"
