---
# Source: tailscale-operator/templates/proxy-rbac.yaml
# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxies
  namespace: tailscale
---
# Source: tailscale-operator/templates/proxy-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proxies
  namespace: tailscale
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch",
      ]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "get"]
---
# Source: tailscale-operator/templates/proxy-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxies
  namespace: tailscale
subjects:
  - kind: ServiceAccount
    name: proxies
    namespace: tailscale
roleRef:
  kind: Role
  name: proxies
  apiGroup: rbac.authorization.k8s.io
