---
# Source: argo-cd/charts/redis-ha/templates/redis-haproxy-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-redis-ha-haproxy
  namespace: "kube-system"
  labels:
    heritage: Helm
    release: argocd
    chart: redis-ha-4.33.7
    app: argocd-redis-ha
