---
# Source: argo-cd/charts/redis-ha/templates/redis-haproxy-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: argocd-redis-ha-haproxy
  namespace: "kube-system"
  labels:
    app: redis-ha
    heritage: "Helm"
    release: "argocd"
    chart: redis-ha-4.33.7
    component: argocd-redis-ha-haproxy
  annotations:
spec:
  type: ClusterIP
  ports:
    - name: tcp-haproxy
      port: 6379
      protocol: TCP
      targetPort: redis
    - name: http-exporter-port
      port: 9101
      protocol: TCP
      targetPort: metrics-port
  selector:
    release: argocd
    app: redis-ha-haproxy
