apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/ryanseipp/gitops-app-platform.git
        revision: HEAD
        directories:
          - path: gitops/apps/*
  template:
    metadata:
      name: "{{ .path.basenameNormalized }}"
    spec:
      project: apps
      source:
        repoURL: https://github.com/ryanseipp/gitops-app-platform.git
        targetRevision: HEAD
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: ""
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
