repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - chart: argo/argo-cd
    name: argocd
    version: 8.3.0
    namespace: kube-system
    values:
      - redis-ha:
          enabled: true
        controller:
          replicas: 1
        server:
          autoscaling:
            enabled: true
            minReplicas: 2
        configs:
          params:
            server.insecure: true
        repoServer:
          autoscaling:
            enabled: true
            minReplicas: 2
        applicationSet:
          replicas: 2
